server:
  port: 8081

mysql:
  host: 127.0.0.1
  port: 3306
  database: hm-dianping
  username: root
  password: 123456

redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  database: 1
oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  bucket: lyl-java-ai-01
  accessKeyId: "your-access-key-id"
  accessKeySecret: "your-access-key-secret"
  publicHost: https://lyl-java-ai-01.oss-cn-beijing.aliyuncs.com
  dir: blogs
